name: generate breakout animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch Breakout SVG files
        run: |
          mkdir -p dist
          curl -s "https://profile-readme-generator.com/api/arcade?username=${{ github.repository_owner }}&game=breakout&theme=dark" -o dist/breakout-contribution-graph-dark.svg
          curl -s "https://profile-readme-generator.com/api/arcade?username=${{ github.repository_owner }}&game=breakout" -o dist/breakout-contribution-graph.svg

      - name: Push animation to pacman-output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: pacman-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
